Repository doctrine/persistence, pull requests merged in 2019-04, with the labels that each got.

#48 Use getManagerForClass in getRepository
  lib/Doctrine/Common/Persistence/AbstractManagerRegistry.php
  tests/Doctrine/Tests/Common/Persistence/ManagerRegistryTest.php
  tests/Doctrine/Tests/Common/Persistence/Mapping/ClassMetadataFactoryTest.php
  tests/Doctrine/Tests/Common/Persistence/Mapping/TestClassMetadataFactory.php
  tests/Doctrine/Tests/Common/Persistence/OtherTestObject.php
  tests/Doctrine/Tests/Common/Persistence/PersistentObjectTest.php
  tests/Doctrine/Tests/Common/Persistence/TestObject.php
Labels: Bug

#54 Deprecate ObjectManager::merge() and ObjectManager::detach()
  UPGRADE-1.2.md
  lib/Doctrine/Common/Persistence/ObjectManager.php
Labels: Deprecation

#55 Deprecate PersistentObject class.
  UPGRADE-1.2.md
  lib/Doctrine/Common/Persistence/PersistentObject.php
Labels: Deprecation

#51 Remove PersistentObject magic object.
  UPGRADE-2.0.md
  lib/Doctrine/Persistence/PersistentObject.php
  phpstan.neon
  tests/Doctrine/Tests/Persistence/ManagerRegistryTest.php
  tests/Doctrine/Tests/Persistence/OtherTestObject.php
  tests/Doctrine/Tests/Persistence/PersistentObjectTest.php
  tests/Doctrine/Tests/Persistence/TestObject.php
Labels: BC Break

#56 Remove dupes in FileDriver::getAllClassNames
  lib/Doctrine/Common/Persistence/Mapping/Driver/FileDriver.php
  tests/Doctrine/Tests/Common/Persistence/Mapping/FileDriverTest.php
Labels: Bug

#50 Add types to all interfaces.
  .gitignore
  .travis.yml
  UPGRADE-2.0.md
  composer.json
  composer.lock
  lib/Doctrine/Persistence/AbstractManagerRegistry.php
  lib/Doctrine/Persistence/ConnectionRegistry.php
  lib/Doctrine/Persistence/Event/LifecycleEventArgs.php
  lib/Doctrine/Persistence/Event/LoadClassMetadataEventArgs.php
  lib/Doctrine/Persistence/Event/ManagerEventArgs.php
  lib/Doctrine/Persistence/Event/OnClearEventArgs.php
  lib/Doctrine/Persistence/Event/PreUpdateEventArgs.php
  lib/Doctrine/Persistence/ManagerRegistry.php
  lib/Doctrine/Persistence/Mapping/AbstractClassMetadataFactory.php
  lib/Doctrine/Persistence/Mapping/ClassMetadata.php
  lib/Doctrine/Persistence/Mapping/ClassMetadataFactory.php
  lib/Doctrine/Persistence/Mapping/Driver/AnnotationDriver.php
  lib/Doctrine/Persistence/Mapping/Driver/DefaultFileLocator.php
  lib/Doctrine/Persistence/Mapping/Driver/FileDriver.php
  lib/Doctrine/Persistence/Mapping/Driver/FileLocator.php
  lib/Doctrine/Persistence/Mapping/Driver/MappingDriver.php
  lib/Doctrine/Persistence/Mapping/Driver/MappingDriverChain.php
  lib/Doctrine/Persistence/Mapping/Driver/PHPDriver.php
  lib/Doctrine/Persistence/Mapping/Driver/StaticPHPDriver.php
  lib/Doctrine/Persistence/Mapping/Driver/SymfonyFileLocator.php
  lib/Doctrine/Persistence/Mapping/MappingException.php
  lib/Doctrine/Persistence/Mapping/ReflectionService.php
  lib/Doctrine/Persistence/Mapping/RuntimeReflectionService.php
  lib/Doctrine/Persistence/Mapping/StaticReflectionService.php
  lib/Doctrine/Persistence/NotifyPropertyChanged.php
  lib/Doctrine/Persistence/ObjectManager.php
  lib/Doctrine/Persistence/ObjectManagerAware.php
  lib/Doctrine/Persistence/ObjectManagerDecorator.php
  lib/Doctrine/Persistence/ObjectRepository.php
  lib/Doctrine/Persistence/PropertyChangedListener.php
  lib/Doctrine/Persistence/Proxy.php
  phpcs.xml.dist
  phpstan.neon
  phpunit.xml.dist
  tests/Doctrine/Tests/DoctrineTestCase.php
  tests/Doctrine/Tests/Persistence/Event/PreUpdateEventArgsTest.php
  tests/Doctrine/Tests/Persistence/ManagerRegistryTest.php
  tests/Doctrine/Tests/Persistence/Mapping/AnnotationDriverTest.php
  tests/Doctrine/Tests/Persistence/Mapping/ClassMetadataFactoryTest.php
  tests/Doctrine/Tests/Persistence/Mapping/DefaultFileLocatorTest.php
  tests/Doctrine/Tests/Persistence/Mapping/DriverChainTest.php
  tests/Doctrine/Tests/Persistence/Mapping/FileDriverTest.php
  tests/Doctrine/Tests/Persistence/Mapping/PHPDriverTest.php
  tests/Doctrine/Tests/Persistence/Mapping/RuntimeReflectionServiceTest.php
  tests/Doctrine/Tests/Persistence/Mapping/StaticPHPDriverTest.php
  tests/Doctrine/Tests/Persistence/Mapping/StaticReflectionServiceTest.php
  tests/Doctrine/Tests/Persistence/Mapping/SymfonyFileLocatorTest.php
  tests/Doctrine/Tests/Persistence/Mapping/TestClassMetadataFactory.php
  tests/Doctrine/Tests/Persistence/Mapping/_files/TestEntity.php
  tests/Doctrine/Tests/Persistence/Mapping/_files/annotation/TestClass.php
  tests/Doctrine/Tests/Persistence/ObjectManagerDecoratorTest.php
  tests/Doctrine/Tests/TestInit.php
Labels: BC Break, Improvement

#61 Add more specific doc block type hints for arrays.
  lib/Doctrine/Persistence/ManagerRegistry.php
  lib/Doctrine/Persistence/Mapping/AbstractClassMetadataFactory.php
  lib/Doctrine/Persistence/Mapping/ClassMetadata.php
  lib/Doctrine/Persistence/Mapping/ClassMetadataFactory.php
  lib/Doctrine/Persistence/Mapping/Driver/FileDriver.php
  lib/Doctrine/Persistence/Mapping/Driver/MappingDriverChain.php
  lib/Doctrine/Persistence/Mapping/MappingException.php
  lib/Doctrine/Persistence/ObjectRepository.php
Labels: Improvement
