Repository doctrine/persistence, pull requests merged in 2021-06, with the labels that each got.

#190 Don't pass null to strpos()
  tests/Doctrine/Tests/Persistence/Mapping/FileDriverTest.php
Labels: Bug

#103 Fix incorrect instance of ReflectionProperty created for public typed properties
  lib/Doctrine/Persistence/Mapping/RuntimeReflectionService.php
  lib/Doctrine/Persistence/Reflection/TypedNoDefaultReflectionProperty.php
  lib/Doctrine/Persistence/Reflection/TypedNoDefaultReflectionPropertyBase.php
  lib/Doctrine/Persistence/Reflection/TypedNoDefaultRuntimePublicReflectionProperty.php
  tests/Doctrine/Tests_PHP74/Persistence/Mapping/RuntimeReflectionServiceTest.php
Labels: Bug

#174 Removed parameter from ObjectManager::clear()
  docs/en/reference/index.rst
  lib/Doctrine/Persistence/ObjectManager.php
  lib/Doctrine/Persistence/ObjectManagerDecorator.php
  tests/Doctrine/Tests/Persistence/ObjectManagerDecoratorTest.php
Labels: BC Break

#193 Add .github, .doctrine-project.json and phpstan-baseline.neon to export ignore
  .gitattributes
Labels: Improvement

#192 Allow null as a return value for association's target
  lib/Doctrine/Common/Persistence/PersistentObject.php
  lib/Doctrine/Persistence/Mapping/ClassMetadata.php
Labels: Bug
