Repository doctrine/persistence, pull requests merged in 2022-04, with the labels that each got.

#273 Make `*EventArgs` generic
  src/Persistence/Event/LifecycleEventArgs.php
  src/Persistence/Event/LoadClassMetadataEventArgs.php
  src/Persistence/Event/ManagerEventArgs.php
  src/Persistence/Event/OnClearEventArgs.php
  src/Persistence/Event/PreUpdateEventArgs.php
Labels: Static Analysis

#276 Flag event templates as covariant
  src/Persistence/Event/LifecycleEventArgs.php
  src/Persistence/Event/LoadClassMetadataEventArgs.php
  src/Persistence/Event/ManagerEventArgs.php
  src/Persistence/Event/OnClearEventArgs.php
  src/Persistence/Event/PreUpdateEventArgs.php
Labels: Static Analysis

#277 Update meta information
  .doctrine-project.json
Labels: Documentation

#278 Remove `doctrine/deprecations`
  composer.json
Labels: Improvement

#280 Document MappingException::pathRequired() removal
  UPGRADE.md
Labels: Documentation

#281 Emit deprecation for LifecycleEventArgs::getEntity
  src/Persistence/Event/LifecycleEventArgs.php
Labels: Improvement

#283 Update metadata
  .doctrine-project.json
Labels: Documentation

#286 Handle anonymous classes more gracefully
  src/Persistence/AbstractManagerRegistry.php
  src/Persistence/Mapping/AbstractClassMetadataFactory.php
  src/Persistence/Mapping/MappingException.php
  tests/Persistence/ManagerRegistryTest.php
  tests/Persistence/Mapping/AbstractClassMetadataFactoryTest.php
Labels: Bug

#287 Fix broken mock
  tests/Persistence/Mapping/AbstractClassMetadataFactoryTest.php
Labels: Test Suite
