Repository doctrine/persistence, pull requests merged in 2022-05, with the labels that each got.

#292 Declare ObjectRepository's template as covariant
  src/Persistence/ObjectRepository.php
Labels: Bug, Static Analysis

#295 Throw an exception when passing an entity alias
  src/Persistence/Mapping/AbstractClassMetadataFactory.php
  tests/Persistence/Mapping/AbstractClassMetadataFactoryTest.php
Labels: Improvement

#296 Fix determining manager for proxied class
  src/Persistence/AbstractManagerRegistry.php
  tests/Persistence/ManagerRegistryTest.php
  tests/Persistence/TestObjectProxy.php
Labels: Bug
