Repository doctrine/persistence, pull requests merged in 2022-03, with the labels that each got.

#246 Decouple from annotations
  UPGRADE-1.2.md
  UPGRADE-2.2.md
  UPGRADE-2.3.md
  UPGRADE.md
  docs/en/reference/index.rst
  lib/Doctrine/Persistence/Mapping/Driver/AnnotationDriver.php
  lib/Doctrine/Persistence/Mapping/Driver/ColocatedMappingDriver.php
  lib/Doctrine/Persistence/Mapping/Driver/StaticPHPDriver.php
  lib/Doctrine/Persistence/Mapping/MappingException.php
  tests/Doctrine/Tests/Persistence/Mapping/AnnotationDriverTest.php
  tests/Doctrine/Tests/Persistence/Mapping/ColocatedMappingDriverTest.php
  tests/Doctrine/Tests/Persistence/Mapping/_files/colocated/TestClass.php
Labels: Deprecation

#248 add enum reflection property
  composer.json
  lib/Doctrine/Persistence/Reflection/EnumReflectionProperty.php
  phpcs.xml.dist
  phpunit.xml.dist
  tests/Doctrine/Tests_PHP81/Persistence/Reflection/EnumReflectionPropertyTest.php
Labels: Enhancement

#250 Document colocated mapping driver upgrade path better
  UPGRADE.md
  src/Persistence/Mapping/Driver/AnnotationDriver.php
Labels: Documentation

#251 Rephrase ObjectManager::merge() BC break doc
  UPGRADE.md
Labels: Documentation

#252 Make templates more precise
  src/Persistence/ManagerRegistry.php
  src/Persistence/ObjectManager.php
  src/Persistence/ObjectRepository.php
Labels: Improvement

#256 Remove unused `VerifyDeprecations` trait
  tests/Persistence/ManagerRegistryTest.php
  tests/Persistence/Mapping/ClassMetadataFactoryTest.php
Labels: Test Suite

#257 Fix nullable parameter types
  src/Persistence/ConnectionRegistry.php
  src/Persistence/ManagerRegistry.php
Labels: Static Analysis

#264 Document `$orderBy` parameter as nullable
  src/Persistence/ObjectRepository.php
Labels: Static Analysis

#265 PHPStan 1.5.0, Psalm 4.22.0
  composer.json
Labels: Static Analysis
