Repository doctrine/persistence, pull requests merged in 2024-05, with the labels that each got.

#354 Maintenance
  .github/dependabot.yml
  .github/workflows/continuous-integration.yml
Labels: CI

#357 fix: Failing to retrieve reflection property on enum
  src/Persistence/Reflection/EnumReflectionProperty.php
  tests_php81/Persistence/Reflection/EnumReflectionPropertyTest.php
Labels: Bug

#360 Remove deprecated classes
  UPGRADE.md
  phpstan-baseline.neon
  phpstan.neon
  src/Persistence/Reflection/RuntimePublicReflectionProperty.php
  src/Persistence/Reflection/TypedNoDefaultReflectionProperty.php
  src/Persistence/Reflection/TypedNoDefaultReflectionPropertyBase.php
  src/Persistence/Reflection/TypedNoDefaultRuntimePublicReflectionProperty.php
  tests/Persistence/RuntimePublicReflectionPropertyTest.php
Labels: BC Break

#363 Upgrade to doctrine/coding-standard v12
  composer.json
  src/Persistence/AbstractManagerRegistry.php
  src/Persistence/Mapping/Driver/StaticPHPDriver.php
  src/Persistence/ObjectManagerDecorator.php
Labels: Static Analysis

#364 Upgrade to PHPStan 1.11.1
  composer.json
  phpstan-baseline.neon
Labels: Static Analysis

#366 Remove composer/package-versions-deprecated
  composer.json
Labels: Improvement

#367 Make data providers static
  tests/Persistence/Mapping/ColocatedMappingDriverTest.php
  tests/Persistence/Mapping/SymfonyFileLocatorTest.php
Labels: Test Suite

#368 Remove support for Doctrine Common proxies
  .github/workflows/coding-standards.yml
  .github/workflows/continuous-integration.yml
  .github/workflows/static-analysis.yml
  CONTRIBUTING.md
  UPGRADE.md
  composer.json
  src/Persistence/Reflection/RuntimeReflectionProperty.php
  tests/Persistence/RuntimeReflectionPropertyTest.php
Labels: Enhancement, BC Break

#362 Handle the correct zero-value
  src/Persistence/Mapping/Driver/FileDriver.php
Labels: Bug

#361 Drop support for PHP < 8.1
  .github/workflows/continuous-integration.yml
  UPGRADE.md
  composer.json
  phpcs.xml.dist
  phpstan-baseline.neon
  phpstan.neon
  phpunit.xml.dist
  psalm-baseline.xml
  src/Persistence/AbstractManagerRegistry.php
  src/Persistence/ConnectionRegistry.php
  src/Persistence/Event/LifecycleEventArgs.php
  src/Persistence/Event/LoadClassMetadataEventArgs.php
  src/Persistence/Event/ManagerEventArgs.php
  src/Persistence/Event/OnClearEventArgs.php
  src/Persistence/Event/PreUpdateEventArgs.php
  src/Persistence/ManagerRegistry.php
  src/Persistence/Mapping/AbstractClassMetadataFactory.php
  src/Persistence/Mapping/ClassMetadata.php
  src/Persistence/Mapping/ClassMetadataFactory.php
  src/Persistence/Mapping/Driver/ColocatedMappingDriver.php
  src/Persistence/Mapping/Driver/DefaultFileLocator.php
  src/Persistence/Mapping/Driver/FileDriver.php
  src/Persistence/Mapping/Driver/FileLocator.php
  src/Persistence/Mapping/Driver/MappingDriver.php
  src/Persistence/Mapping/Driver/MappingDriverChain.php
  src/Persistence/Mapping/Driver/PHPDriver.php
  src/Persistence/Mapping/Driver/StaticPHPDriver.php
  src/Persistence/Mapping/Driver/SymfonyFileLocator.php
  src/Persistence/Mapping/MappingException.php
  src/Persistence/Mapping/ReflectionService.php
  src/Persistence/Mapping/RuntimeReflectionService.php
  src/Persistence/Mapping/StaticReflectionService.php
  src/Persistence/NotifyPropertyChanged.php
  src/Persistence/ObjectManager.php
  src/Persistence/ObjectManagerDecorator.php
  src/Persistence/ObjectRepository.php
  src/Persistence/PropertyChangedListener.php
  src/Persistence/Proxy.php
  src/Persistence/Reflection/EnumReflectionProperty.php
  src/Persistence/Reflection/RuntimeReflectionProperty.php
  src/Persistence/Reflection/TypedNoDefaultReflectionProperty.php
  tests/Persistence/ManagerRegistryTest.php
  tests/Persistence/Mapping/AbstractClassMetadataFactoryTest.php
  tests/Persistence/Mapping/ClassMetadataFactoryTest.php
  tests/Persistence/Mapping/FileDriverTest.php
  tests/Persistence/Mapping/Fixtures/TestClassMetadata.php
  tests/Persistence/Mapping/RuntimeReflectionServiceTest.php
  tests/Persistence/Mapping/StaticReflectionServiceTest.php
  tests/Persistence/Mapping/SymfonyFileLocatorTest.php
  tests/Persistence/Mapping/TestClassMetadataFactory.php
  tests/Persistence/ObjectManagerDecoratorTest.php
  tests/Persistence/OtherTestObject.php
  tests/Persistence/Reflection/Reflection/EnumReflectionPropertyTest.php
  tests/Persistence/Reflection/TypedNoDefaultReflectionPropertyTest.php
  tests/Persistence/RuntimeReflectionPropertyTest.php
  tests/Persistence/TestObject.php
  tests_php74/Persistence/Mapping/RuntimeReflectionServiceTest.php
Labels: Improvement, BC Break

#369 Implement isUninitializedObject() in ObjectManagerDecorator
  composer.json
  phpstan-baseline.neon
  src/Persistence/ObjectManagerDecorator.php
  tests/Persistence/ObjectManagerDecoratorTest.php
Labels: Enhancement

#371 Replace comment with real method signature
  UPGRADE.md
  phpstan-baseline.neon
  src/Persistence/ObjectManager.php
  src/Persistence/ObjectManagerDecorator.php
  tests/Persistence/ObjectManagerDecoratorTest.php
Labels: BC Break
